export const data = [
  {
    id: 1,
    storageAccount: "01_alpha_",
    version: "Vault v2",
    accountKey: "(multiple)",
    bucketCount: 0,
    size: 0.0,
  },
  {
    id: 2,
    storageAccount: "AccNov16",
    version: "Vault v2",
    accountKey: "",
    bucketCount: 2,
    size: 3.54,
  },
  {
    id: 3,
    storageAccount: "account002",
    version: "Vault v2",
    accountKey: "",
    bucketCount: 1,
    size: 0.0,
  },
  {
    id: 4,
    storageAccount: "AccountLuke_356",
    version: "Vault v2",
    accountKey: "",
    bucketCount: 0,
    size: 0.0,
  },
  {
    id: 5,
    storageAccount: "apptest",
    version: "Vault v1",
    accountKey: "",
    bucketCount: 1,
    size: 0.0,
  },
  {
    id: 6,
    storageAccount: "Customertest",
    version: "Vault v2",
    accountKey: "(multiple)",
    bucketCount: 1,
    size: 1.02,
  },
];
